### ISSUE TITLE
Potential Security Vulnerability: Logs are public

### ISSUE THREAD

**Issue by Xenarc** [grendel-consulting/corporate-frontend#1254]
# Potential Security Vulnerability:

Looks like I found some of your logs are publically available (from Google), even though [https://depshield.sonatype.org/error/grendel-consulting/corporate-frontend/](https://depshield.sonatype.org/error/grendel-consulting/corporate-frontend/) requires an auth token.

URL is:

[https://depshield.sonatype.org/error/grendel-consulting/corporate-frontend/D3PqcVDyA5srY0wMRGpVUQ](https://depshield.sonatype.org/error/grendel-consulting/corporate-frontend/D3PqcVDyA5srY0wMRGpVUQ)

**Comment by ramirezj** [comment]
Appreciate you raising this, @Xenarc; its my understanding this is a generic error exposing some limited information related to DepShield or NPM, rather than anything specific to Grendel Consulting, so will close the issue in a day or so

**Comment by Xenarc** [comment]
No worries, just saw it and thought it could be an potential problem, especially given that you could access it through a simple google search.
